export const footerData = {
  brand: {
    name: 'Zyphuel',
    logoPath: '/images/Zyphuel-logo.png',
    logoAlt: 'Zyphuel - Pakistan No.1 Mobile Fuel Supplier & Best Mobile Application for Fuel Suppliers',
    fallbackLogo: true, // triggers SVG if image fails
    description:
      'Zyphuel is Pakistan\'s #1 mobile fuel delivery brand, supplier, and agency. Providing international-standard, 24/7 on-demand petrol and diesel fuel delivery across Lahore.',
  },
  contact: {
    phone: '+92 3230-112464',
    email: 'm.daniyalkhan490@gmail.com',
    address: '75-Main Boulevard, Gulberg III, Lahore, Pakistan',
    whatsapp: 'https://wa.me/923230112464',
  },
  socialLinks: [
    {
      platform: 'Facebook',
      url: 'https://www.facebook.com/muhammad.daniyal.522942/',
      icon: 'fa-brands fa-facebook-f',
      title: 'Zyphuel Official Facebook Page & Community',
    },
    {
      platform: 'Google Business Profile',
      url: 'https://share.google/Nb4XGKYq5aU0nzLr3',
      icon: 'fa-brands fa-google',
      title: 'Zyphuel Google Business & Maps Location Lahore',
    },
    {
      platform: 'LinkedIn Company',
      url: 'https://www.linkedin.com/company/zyphuel/?viewAsMember=true',
      icon: 'fa-brands fa-linkedin',
      title: 'Zyphuel Official LinkedIn Company Page',
    },
    {
      platform: 'LinkedIn Profile',
      url: 'https://www.linkedin.com/in/muhammad-daniyal490',
      icon: 'fa-brands fa-linkedin-in',
      title: 'Muhammad Daniyal - Founder & CEO LinkedIn Profile',
    },
    {
      platform: 'GitHub Profile',
      url: 'https://github.com/daniyal44',
      icon: 'fa-brands fa-github',
      title: 'Muhammad Daniyal GitHub Open Source Portfolio',
    },
  ],
  quickLinks: [
    { label: 'Home', to: '/' },
    { label: 'Services & Rates', to: '/services' },
    { label: 'About Us & Team', to: '/about' },
    { label: 'Order Fuel Dispatch', to: '/order' },
    { label: 'Contact Helpline', to: '/contact' },
    { label: 'Download Mobile App', to: '/download' },
    { label: 'Privacy Policy', to: '/privacy-policy' },
    { label: 'Terms of Use', to: '/terms-of-use' },
  ],
  lahoreTowns: [
    'DHA (Phase 1-9)',
    'Gulberg',
    'Johar Town',
    'Model Town',
    'Wapda Town',
    'Cantonment',
    'Bahria Town',
    'Valencia Town',
    'Faisal Town',
    'Garden Town',
    'Iqbal Town',
    'Township',
    'Shadbagh',
    'Samanabad',
    'Mughalpura',
    'Liaquatabad',
    'Shalimar',
    'Ravi Town',
    'Aziz Bhatti Town',
    'Data Gunj Bakhsh Town',
  ],
  expansion: {
    showAlert: true,
    text: 'Launching micro-hubs in Rawalpindi, Islamabad, and Karachi shortly.',
    badge: 'Islamabad Coming Soon',
  },
  bottomLinks: [
    { label: 'Privacy Policy', to: '/privacy-policy' },
    { label: 'Terms of Use', to: '/terms-of-use' },
  ],
  copyright: `© ${new Date().getFullYear()} Zyphuel Pakistan. All rights reserved.`,
};