export const footerData = {
  brand: {
    name: 'Zyphuel',
    logoPath: '/images/Zyphuel-logo.png',
    logoAlt: 'Zyphuel - Mobile Fuel Delivery Service Lahore',
    fallbackLogo: true, // triggers SVG if image fails
    description:
      'Zyphuel provides 24/7 on-demand doorstep petrol and diesel fuel delivery across Lahore with calibrated digital flow meters and real-time GPS tracking.',
  },
  contact: {
    phone: '+92 3230-112464',
    email: 'm.daniyalkhan490@gmail.com',
    address: '75-Main Boulevard, Gulberg III, Lahore, Pakistan',
    whatsapp: 'https://wa.me/923230112464',
  },
  socialLinks: [
    {
      platform: 'Facebook',
      url: 'https://www.facebook.com/muhammad.daniyal.522942/',
      icon: 'fa-brands fa-facebook-f',
      title: 'Zyphuel Official Facebook Page & Community',
    },
    {
      platform: 'Google Business Profile',
      url: 'https://share.google/Nb4XGKYq5aU0nzLr3',
      icon: 'fa-brands fa-google',
      title: 'Zyphuel Google Business & Maps Location Lahore',
    },
    {
      platform: 'LinkedIn Company',
      url: 'https://www.linkedin.com/company/zyphuel/',
      icon: 'fa-brands fa-linkedin',
      title: 'Zyphuel Official LinkedIn Company Page',
    },
    {
      platform: 'LinkedIn Profile',
      url: 'https://www.linkedin.com/in/muhammad-daniyal490',
      icon: 'fa-brands fa-linkedin-in',
      title: 'Muhammad Daniyal - Founder & CEO LinkedIn Profile',
    },
    {
      platform: 'GitHub Profile',
      url: 'https://github.com/daniyal44',
      icon: 'fa-brands fa-github',
      title: 'Muhammad Daniyal GitHub Open Source Portfolio',
    },
  ],
  quickLinks: [
    { label: 'Home', to: '/' },
    { label: 'Services & Rates', to: '/services/' },
    { label: 'About Us & Team', to: '/about/' },
    { label: 'Blog & Articles', to: '/blog/' },
    { label: 'Order Fuel Dispatch', to: '/order/' },
    { label: 'Contact Helpline', to: '/contact/' },
    { label: 'Download Mobile App', to: '/download/' },
  ],
  lahoreTowns: [
    'DHA (Phase 1-9)',
    'Gulberg',
    'Johar Town',
    'Model Town',
    'Wapda Town',
    'Cantonment',
    'Bahria Town',
    'Valencia Town',
    'Faisal Town',
    'Garden Town',
    'Iqbal Town',
    'Township',
    'Shadbagh',
    'Samanabad',
    'Mughalpura',
    'Liaquatabad',
    'Shalimar',
    'Ravi Town',
    'Aziz Bhatti Town',
    'Data Gunj Bakhsh Town',
  ],
  expansion: {
    showAlert: true,
    text: 'Launching micro-hubs in Rawalpindi, Islamabad, and Karachi shortly.',
    badge: 'Islamabad Coming Soon',
  },
  bottomLinks: [
    { label: 'Privacy Policy', to: '/privacy/' },
    { label: 'Terms of Use', to: '/terms/' },
  ],
  copyright: `© ${new Date().getFullYear()} Zyphuel Pakistan. All rights reserved.`,
};